### ISSUE TITLE
Teamshield package with Gazebo simulation

### ISSUE THREAD

**Issue by klutzzykitty** [madsciencetist/teamshield#1]
Just checked out the teamshied ros package and although I guess its awfully late to reach out, I think its still a cool terminal demo 
to show 3 drones that communicate with each other. (Fixed some compatibility issues and got it working on ROS Noetic).

Was wondering if there was any work done with having teamshield ros package working with a Gazebo simulation of 3 drones so that it can be better visualized. 

If so, can that be shared? 
Else you can also point out what can be used to have a gazebo simulation along with the teahshield ROS package. 

Thanks @madsciencetist 

PS: Although this is not an issue, asking here as there's no discussion tab.

**Comment by madsciencetist** [comment]
Oh man, 7-year-old hackathon code with no readme! What was this!

This was never integrated with gazebo, but we must have had at least a 2D visualizer. I don't remember whether we wrote it during the hackathon but didn't include it here, or whether the hackathon provided it. Either way, I don't have it.

It would be much easier to visualize with Rviz (or something custom) than Gazebo. Each drone publishes a `current_location` topic which you could change from `Point` to `PointStamped` to be compatible with the default Rviz plugin. To visualize the quadtree map, you'd need to convert it to an OccupancyGrid.

But don't bother. This code doesn't even look complete. Every agent just flies to (100, 100, 100). The planner receives the map but doesn't look at it. The estimator receives other agents' maps but doesn't merge them with its own. Everything is a TODO. Abandon this foolish endeavor.

**Comment by klutzzykitty** [comment]
Haha! 
Makes sense lol. Had some tinkering to do with getting it up, but was a good one. 
Nice idea tho. Can think of creating a completely new one which can be simulated and visualized.
